apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: k254a0p68-go 
  janus-idp.io/tekton: k254a0p68-go
  backstage.io/kubernetes-id: k254a0p68-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: k254a0p68-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml