apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: k254a0p68-go
  janus-idp.io/tekton: k254a0p68-go
  backstage.io/kubernetes-id: k254a0p68-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: k254a0p68-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
